name: Lint Check
on:
  workflow_call:

jobs:
  yaml-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
         node-version: 20

      - name: Install dependence
        run: cd tests && yarn install

      - name: Check yaml
        run: cd tests && node index.js && cd ..

      - name: Clean Workspace
        run: perl tests/clean.pl

  sh-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lint: [shellcheck, shfmt]

    steps:
      - uses: actions/checkout@v4
      - name: ShellCheck lint
        if: matrix.lint == 'shellcheck'
        uses: ludeeus/action-shellcheck@2.0.0

      - name: shfmt lint
        if: matrix.lint == 'shfmt'
        run: |
            wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.4-2_amd64.deb && sudo dpkg -i libtinfo5_6.4-2_amd64.deb && rm -f libtinfo5_6.4-2_amd64.deb
            wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libncurses5_6.4-2_amd64.deb && sudo dpkg -i libncurses5_6.4-2_amd64.deb && rm -f libncurses5_6.4-2_amd64.deb
            sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
            export HOST_ARCH=$(dpkg --print-architecture)
            case ${HOST_ARCH} in
                armv7* | armv8l | armhf | arm) aria2c https://github.com/mvdan/sh/releases/download/v3.8.0/shfmt_v3.8.0_linux_arm -o shfmt ;;
                i*86 | x86) aria2c https://github.com/mvdan/sh/releases/download/v3.8.0/shfmt_v3.8.0_linux_x86 -o shfmt ;;
                amd64 | x86_64) aria2c https://github.com/mvdan/sh/releases/download/v3.8.0/shfmt_v3.8.0_linux_amd64 -o shfmt ;;
                aarch64 | arm64) aria2c https://github.com/mvdan/sh/releases/download/v3.8.0/shfmt_v3.8.0_linux_arm64 -o shfmt ;;

                *) echo "Unknow cpu architecture for this device !" && exit 1 ;;
            esac
            chmod 755 -R ./shfmt
            ./shfmt -w -i 2 kernelsu/ksupatch.sh

      - name: Clean Workspace
        run: perl tests/clean.pl

